In [ ]:
from google.colab import files 
uploaded = files.upload()

Saving drug200.csv to drug200.csv

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from sklearn import linear_model

/usr/local/lib/python3.7/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)

In [ ]:
df=pd.read_csv('drug200.csv')

In [ ]:
df.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [ ]:
age_groups = []
for i in df['Age']:
    if i <= 30:
        age_groups.append('0-30')
    if i > 30 and i <= 40:
        age_groups.append('30-40')
    if i > 40 and i <= 50:
        age_groups.append('40-50')
    if i > 50 and i <= 60:
        age_groups.append('50-60')
    if i > 60:
        age_groups.append('60+')
        na_to_k_groups = []
for i in df["Na_to_K"]:
    if i <= 10:
        na_to_k_groups.append('5-10')
    if i > 10 and i <= 15:
        na_to_k_groups.append('10-15')
    if i > 15 and i <= 20:
        na_to_k_groups.append('15-20')
    if i > 20 and i <= 25:
        na_to_k_groups.append('20-25')
    if i > 25 and i <= 30:
        na_to_k_groups.append('25-30')
    if i > 30:
        na_to_k_groups.append('30+')

df['AgeGroup'] = age_groups

In [ ]:
df

     Age Sex      BP Cholesterol  Na_to_K   Drug AgeGroup
0     23   F    HIGH        HIGH   25.355  DrugY     0-30
1     47   M     LOW        HIGH   13.093  drugC    40-50
2     47   M     LOW        HIGH   10.114  drugC    40-50
3     28   F  NORMAL        HIGH    7.798  drugX     0-30
4     61   F     LOW        HIGH   18.043  DrugY      60+
..   ...  ..     ...         ...      ...    ...      ...
195   56   F     LOW        HIGH   11.567  drugC    50-60
196   16   M     LOW        HIGH   12.006  drugC     0-30
197   52   M  NORMAL        HIGH    9.894  drugX    50-60
198   23   M  NORMAL      NORMAL   14.020  drugX     0-30
199   40   F     LOW      NORMAL   11.349  drugX    30-40

[200 rows x 7 columns]

In [ ]:
na_to_k_groups = []
for i in df["Na_to_K"]:
    if i <= 10:
        na_to_k_groups.append('5-10')
    if i > 10 and i <= 15:
        na_to_k_groups.append('10-15')
    if i > 15 and i <= 20:
        na_to_k_groups.append('15-20')
    if i > 20 and i <= 25:
        na_to_k_groups.append('20-25')
    if i > 25 and i <= 30:
        na_to_k_groups.append('25-30')
    if i > 30:
        na_to_k_groups.append('30+')

df['Na_to_K_groups'] = na_to_k_groups
df

     Age Sex      BP Cholesterol  Na_to_K   Drug AgeGroup Na_to_K_groups
0     23   F    HIGH        HIGH   25.355  DrugY     0-30          25-30
1     47   M     LOW        HIGH   13.093  drugC    40-50          10-15
2     47   M     LOW        HIGH   10.114  drugC    40-50          10-15
3     28   F  NORMAL        HIGH    7.798  drugX     0-30           5-10
4     61   F     LOW        HIGH   18.043  DrugY      60+          15-20
..   ...  ..     ...         ...      ...    ...      ...            ...
195   56   F     LOW        HIGH   11.567  drugC    50-60          10-15
196   16   M     LOW        HIGH   12.006  drugC     0-30          10-15
197   52   M  NORMAL        HIGH    9.894  drugX    50-60           5-10
198   23   M  NORMAL      NORMAL   14.020  drugX     0-30          10-15
199   40   F     LOW      NORMAL   11.349  drugX    30-40          10-15

[200 rows x 8 columns]

In [ ]:
df = df[['AgeGroup','Sex','BP','Cholesterol','Na_to_K_groups','Drug']]
df

    AgeGroup Sex      BP Cholesterol Na_to_K_groups   Drug
0       0-30   F    HIGH        HIGH          25-30  DrugY
1      40-50   M     LOW        HIGH          10-15  drugC
2      40-50   M     LOW        HIGH          10-15  drugC
3       0-30   F  NORMAL        HIGH           5-10  drugX
4        60+   F     LOW        HIGH          15-20  DrugY
..       ...  ..     ...         ...            ...    ...
195    50-60   F     LOW        HIGH          10-15  drugC
196     0-30   M     LOW        HIGH          10-15  drugC
197    50-60   M  NORMAL        HIGH           5-10  drugX
198     0-30   M  NORMAL      NORMAL          10-15  drugX
199    30-40   F     LOW      NORMAL          10-15  drugX

[200 rows x 6 columns]

In [ ]:
x, y = df.values[:, :-1], df.values[:, -1]
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.33)
x_train = pd.get_dummies(pd.DataFrame(x_train))
x_test = pd.get_dummies(pd.DataFrame(x_test))

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)

In [ ]:
x_test

    0_0-30  0_30-40  0_40-50  0_50-60  ...  4_20-25  4_25-30  4_30+  4_5-10
0        0        0        0        1  ...        0        1      0       0
1        0        0        1        0  ...        0        0      1       0
2        0        0        1        0  ...        0        0      1       0
3        1        0        0        0  ...        0        0      0       0
4        0        0        1        0  ...        0        0      1       0
..     ...      ...      ...      ...  ...      ...      ...    ...     ...
61       1        0        0        0  ...        0        0      0       0
62       1        0        0        0  ...        0        0      0       0
63       0        1        0        0  ...        0        0      0       0
64       0        0        1        0  ...        0        0      0       0
65       1        0        0        0  ...        0        0      1       0

[66 rows x 18 columns]

In [ ]:
t=[[0,0,0,1,0,1,0,0,1,0,1,0,1,0,0,0,0,0]]

In [ ]:
log_reg = linear_model.LogisticRegression(max_iter = 5000)
log_reg.fit(x_train, y_train)
log_reg_tacc=100*log_reg.score(x_train, y_train)
print('Logistic Regression Predictions: \n', log_reg.predict(x_test), '\n Accuracy:', log_reg_acc, '%')

Logistic Regression Predictions:
 ['DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'drugC' 'DrugY' 'drugB' 'DrugY'
 'drugX' 'drugX' 'DrugY' 'drugA' 'drugC' 'drugX' 'DrugY' 'DrugY' 'drugX'
 'drugB' 'drugC' 'DrugY' 'drugX' 'drugX' 'drugA' 'drugX' 'DrugY' 'drugB'
 'drugX' 'drugA' 'DrugY' 'drugX' 'drugA' 'drugA' 'DrugY' 'drugC' 'DrugY'
 'DrugY' 'drugA' 'DrugY' 'drugX' 'drugB' 'drugX' 'drugA' 'drugB' 'DrugY'
 'DrugY' 'DrugY' 'drugX' 'DrugY' 'drugC' 'drugB' 'DrugY' 'DrugY' 'drugC'
 'drugB' 'DrugY' 'drugC' 'drugX' 'drugX' 'DrugY' 'drugX' 'DrugY' 'DrugY'
 'drugX' 'drugC' 'DrugY']
 Accuracy: 100.0 %

In [ ]:
temp=[[1,0,0,0,0,0,1,0,0,1,1,0,0,1,0,0,0,0]]
1,0,0,0,0,0,1,0,0,1,1,0,0,1,0,0,0,0
predictedres=log_reg.predict(temp)
predictedres

array(['DrugY'], dtype=object)

In [ ]:
from sklearn.externals import joblib
joblib.dump(log_reg,'lrfile.pkl')

/usr/local/lib/python3.7/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)

['lrfile.pkl']